<a href="https://colab.research.google.com/github/Pradeepa06/Training-a-classifier/blob/main/Habana_TPC_commonly_used_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

torch.add

In [11]:
import torch
x=torch.tensor([3.5,4,67,42,982])
print('X is ',x)
y=torch.add(x,25253.53)
print('Result is',y)

X is  tensor([  3.5000,   4.0000,  67.0000,  42.0000, 982.0000])
Result is tensor([25257.0293, 25257.5293, 25320.5293, 25295.5293, 26235.5293])


torch.sub

In [13]:
import torch
x= torch.rand(2,2)
print('X is',x)
y= torch.rand(2,2)
print('Y is',y)
z=torch.sub(x,y)
print(z)

X is tensor([[0.8002, 0.9441],
        [0.5257, 0.2737]])
Y is tensor([[0.4668, 0.2431],
        [0.1651, 0.3589]])
tensor([[ 0.3334,  0.7010],
        [ 0.3606, -0.0853]])


torch.mul

In [ ]:
import torch
x=torch.rand(3,2)
print('X is ',x)
y=torch.rand(3,2)
print('Y is ',x)
a=torch.mul(x,y)
print('Result is',a)

X is  tensor([[0.8525, 0.2993],
        [0.6547, 0.8897],
        [0.9786, 0.9396]])
Y is  tensor([[0.8525, 0.2993],
        [0.6547, 0.8897],
        [0.9786, 0.9396]])
Result is tensor([[0.1712, 0.0872],
        [0.6161, 0.6987],
        [0.8403, 0.7149]])


torch.div

In [ ]:
import torch
x=torch.rand(3)
print('X is',x)
y=torch.div(x,2)
print('Result is',y)

X is tensor([0.8888, 0.7731, 0.2212])
Result is tensor([0.4444, 0.3866, 0.1106])


torch.transpose

In [29]:
import torch
x= torch.rand(5,3)
print('X val is ',x)
y=torch.transpose(x,1,-2)
print('Result is',y)

X val is  tensor([[0.6288, 0.5125, 0.1168],
        [0.8923, 0.9187, 0.4034],
        [0.9842, 0.2340, 0.3434],
        [0.7013, 0.4291, 0.8367],
        [0.3160, 0.7848, 0.0768]])
Result is tensor([[0.6288, 0.8923, 0.9842, 0.7013, 0.3160],
        [0.5125, 0.9187, 0.2340, 0.4291, 0.7848],
        [0.1168, 0.4034, 0.3434, 0.8367, 0.0768]])


torch.concat


In [53]:
import torch
x=torch.tensor([2,3,57,2.6,23,657,858,342])
y=torch.tensor([563.63,32,0,425.6,11])
print('X and y val is\n ',x,y)
z=torch.cat((x,y),dim=0)
print('Result is',z)
print('Additonal changes') # size is n = > split- > n/splitvalue
x1=torch.split(z,3,dim=0)
print('split data is ',x1)
y1=torch.chunk(z,3,dim=0) # size is n => chunk - > n/chunkvalue pairs view of input tensor
print('Chunk data is ',y1)

X and y val is
  tensor([  2.0000,   3.0000,  57.0000,   2.6000,  23.0000, 657.0000, 858.0000,
        342.0000]) tensor([563.6300,  32.0000,   0.0000, 425.6000,  11.0000])
Result is tensor([  2.0000,   3.0000,  57.0000,   2.6000,  23.0000, 657.0000, 858.0000,
        342.0000, 563.6300,  32.0000,   0.0000, 425.6000,  11.0000])
Additonal changes
split data is  (tensor([ 2.,  3., 57.]), tensor([  2.6000,  23.0000, 657.0000]), tensor([858.0000, 342.0000, 563.6300]), tensor([ 32.0000,   0.0000, 425.6000]), tensor([11.]))
Chunk data is  (tensor([ 2.0000,  3.0000, 57.0000,  2.6000, 23.0000]), tensor([657.0000, 858.0000, 342.0000, 563.6300,  32.0000]), tensor([  0.0000, 425.6000,  11.0000]))


In [108]:
import torch

torch.arange(100).chunk(25, dim=0)
# torch.arange(7).split(2, dim=0)

(tensor([0, 1, 2, 3]),
 tensor([4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11]),
 tensor([12, 13, 14, 15]),
 tensor([16, 17, 18, 19]),
 tensor([20, 21, 22, 23]),
 tensor([24, 25, 26, 27]),
 tensor([28, 29, 30, 31]),
 tensor([32, 33, 34, 35]),
 tensor([36, 37, 38, 39]),
 tensor([40, 41, 42, 43]),
 tensor([44, 45, 46, 47]),
 tensor([48, 49, 50, 51]),
 tensor([52, 53, 54, 55]),
 tensor([56, 57, 58, 59]),
 tensor([60, 61, 62, 63]),
 tensor([64, 65, 66, 67]),
 tensor([68, 69, 70, 71]),
 tensor([72, 73, 74, 75]),
 tensor([76, 77, 78, 79]),
 tensor([80, 81, 82, 83]),
 tensor([84, 85, 86, 87]),
 tensor([88, 89, 90, 91]),
 tensor([92, 93, 94, 95]),
 tensor([96, 97, 98, 99]))

In [107]:
torch.arange(100).split(25, dim=0)

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19, 20, 21, 22, 23, 24]),
 tensor([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
         43, 44, 45, 46, 47, 48, 49]),
 tensor([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
         68, 69, 70, 71, 72, 73, 74]),
 tensor([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
         93, 94, 95, 96, 97, 98, 99]))

torch.reshape

In [11]:
import torch
a=torch.rand(6).reshape(3,2)
print('Result is\n',a)

Result is
 tensor([[0.1224, 0.4981],
        [0.2577, 0.2537],
        [0.5807, 0.0296]])


torch.slice

In [27]:
#2
import torch
a= torch.tensor([2,3,4,5,6,7,8])
print('Slicing')
print(a[2:])
print(a[-1:])
print(a[:-1])
print(a[:])
print(a[:2])
print(a[0:])
print(a[2:5])
print('Indexing')

print(a[-1])


Slicing
tensor([4, 5, 6, 7, 8])
tensor([8])
tensor([2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7, 8])
tensor([2, 3])
tensor([2, 3, 4, 5, 6, 7, 8])
tensor([4, 5, 6])
Indexing
tensor(8)


tensor([2, 3])


torch.ge

In [31]:
import torch
a=torch.tensor([2,3,5,6])
b=torch.tensor([2,5,72,2])
c=torch.ge(a,b)
d=torch.gt(a,b)
print(' GE Result is',c)
print(' GT Result is',d)


 GE Result is tensor([ True, False, False,  True])
 GT Result is tensor([False, False, False,  True])


torch.lt

In [32]:
import torch
a=torch.tensor([12,3,5,236])
b=torch.tensor([2,5,72,236])
c=torch.le(a,b)
d=torch.lt(a,b)
print(' LE Result is',c)
print(' LT Result is',d)


 LE Result is tensor([False,  True,  True,  True])
 LT Result is tensor([False,  True,  True, False])


PyTest 

In [41]:
word="Pradeepa"

In [42]:
assert word== "Pradeepa","Incorrect"

In [230]:
%%file math_1.py

def add(x,y):
  return x+y

def check(x):
   return x


Overwriting math_1.py


In [231]:
%%file test_math_1.py

import math_1
import torch

def test_add():

  assert math_1.add(5,5)==10

def test_check():
  x=torch.tensor([1,3])
  assert(x,math_1.check(torch.tensor([1,3])))

Overwriting test_math_1.py


In [232]:
!pytest test_math_1.py

============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.6.4, py-1.8.0, pluggy-0.7.1
rootdir: /content, inifile:
collected 2 items                                                              

test_math_1.py ..                                                        [100%]

=============================== warnings summary ===============================
test_math_1.py:11
  assertion is always true, perhaps remove parentheses?

-- Docs: http://doc.pytest.org/en/latest/warnings.html
===================== 2 passed, 1 warnings in 0.53 seconds =====================


#Assignment 1 - Linspace 
##1.Linspace - Builtin
##2.Linspace - Custom ops

In [1]:
import torch
print('Linspace') 
x=torch.linspace(3,10,5)
print(x)

x1=3
x2=10
n=5
a=torch.sub(x2,x1)
b=torch.sub(n,1) 
c=torch.div(a,b) 
x1=c
x=torch.range(3,10,step=x1)
print('custom ops')
print(x)

Linspace
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
custom ops
tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  del sys.path[0]


##Pytest for Linspace builtin

In [119]:
%%file math_2.py

import torch

def compute_function(start,end,steps):

  x=torch.linspace(start,end,steps)
  
  return x




Overwriting math_2.py


In [120]:
%%file test_math_2.py

import math_2
import torch

def test_compute_function():
 
  x=torch.Tensor([2.0000,5.2500,8.5000,11.7500,15.0000])

  assert x,math_2.compute_function(2,15,5)
  


Overwriting test_math_2.py


In [121]:
!pytest -v test_math_2.py

============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.6.4, py-1.8.0, pluggy-0.7.1 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /content, inifile:
collected 1 item                                                               

test_math_2.py::test_compute_function FAILED                             [100%]

=================================== FAILURES ===================================
____________________________ test_compute_function _____________________________

    def test_compute_function():
    
      x=torch.Tensor([2.0000,5.2500,8.5000,11.7500,15.0000])
    
>     assert x,math_2.compute_function(2,15,5)
E     RuntimeError: bool value of Tensor with more than one value is ambiguous

test_math_2.py:9: RuntimeError
=========================== 1 failed in 0.55 seconds ===========================


PyTest for Custom ops

In [96]:
%%file math_2.py

import torch

X=torch.linspace(3,10,5)

def compute_function(start,end,steps):

  # x1=3
  # x2=10
  # n=5
  a=torch.sub(end,start)
  b=torch.sub(steps,1)
  c=torch.div(a,b)
  x1=c
  m=start
  n=end
  x=torch.range(m,n,x1)

  return x
  

# x1=3
# x2=10
# n=5
# a=torch.sub(x2,x1) 
# b=torch.sub(n,1) 
# c=torch.div(a,b) 
# x1=c
# x=torch.range(3,10,step=x1)
# print('custom ops')
# print(x)

  
#   return x


Overwriting math_2.py


In [122]:
%%file test_math_2.py

import math_2
import torch

def test_compute_function():
  X=torch.linspace(3,10,5)
  Y=math_2.compute_function(3,10,5)
  assert torch.equal(X,Y)
 

  
  


Overwriting test_math_2.py


In [123]:
!pytest -v test_math_2.py

============================= test session starts ==============================
platform linux2 -- Python 2.7.17, pytest-3.6.4, py-1.8.0, pluggy-0.7.1 -- /usr/bin/python2
cachedir: .pytest_cache
rootdir: /content, inifile:
collected 1 item                                                               

test_math_2.py::test_compute_function PASSED                             [100%]

=========================== 1 passed in 0.49 seconds ===========================
